name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ENVIRONMENT: "staging"
  IMAGE_BASE: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  IMAGE_TAG: "staging"
  IMAGE_PATH: docker/staging

concurrency:
  group: "staging"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.IMAGE_PATH }}/Dockerfile
          tags: ghcr.io/${{ env.IMAGE_BASE }}:${{ env.IMAGE_TAG }}
          push: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'staging' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: saturdayshdev/portainer-deploy@1.3.12
        with:
          url: ${{ secrets.PORTAINER_URL }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpoint: ${{ vars.PORTAINER_ENDPOINT }}
          name: ${{ env.ENVIRONMENT }}-${{ github.event.repository.name }}
          path: ${{ env.IMAGE_PATH }}/docker-compose.yml
          pull: true
          prune: false
          env: ${{ vars.ENVFILE }}
